### ISSUE TITLE
leg calc example is not working

### ISSUE THREAD

**Issue by vadimtk** [knieriem/markdown#9]
when I build calc from `cmd/legcalc` , it is not working properly,
it returns
`2:0: unexpected character '
'`

on anything I enter

**Comment by knieriem** [comment]
It should be fixed now by the three most recent changesets to knieriem/peg.
The bug was introduced with commit [4d76100](https://github.com/knieriem/peg/commit/4d76100), and, as it turned out, another - related -
issue got introduced by commit [0f6dd9d](https://github.com/knieriem/peg/commit/0f6dd9d).

(I have also activated the issue tracker in my fork of the peg project)
